# DEEP LEARNING

## Pytorch Basic



In [3]:
%pip install torch

^C
Note: you may need to restart the kernel to use updated packages.


In [3]:
import torch

In [4]:
torch.cuda.is_available()

False

Dataset with Pytorch

In [5]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('./Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [6]:
df.shape

(150, 6)

In [7]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
x = df.drop(["Species"], axis=1).values
y = le.fit_transform(df["Species"].values)

# Chia dữ liệu với test size = 20%
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

x_train = torch.FloatTensor(x_train)
x_test = torch.FloatTensor(x_test)
y_train = torch.LongTensor(y_train).reshape(-1, 1)
y_test = torch.LongTensor(y_test).reshape(-1, 1)


In [8]:
len(y_train)

120

In [9]:
lables, counts = y_train.unique(return_counts=True)
print(lables, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


# Tính đạo hàm bằng Pytorch

# cho y = 2x^4 + x^3 + 3x^2 + 5x + 1

# Tính y'

In [11]:
import torch

In [12]:
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [13]:
# Định nghĩa hàm
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [14]:
y.grad_fn

In [15]:
# Thực hiện lan truyền ngược và tính toán gradient

y.backward()

In [16]:
x.grad

tensor(93.)

# BTVN 01

Cho y = 5x^5 + 6x^3 - 3x + 1

Cho biết độ dốc của đa thức trên ở điểm nào

In [32]:
x = torch.tensor(1.0, requires_grad=True)

# Hàm y
y = 5*x**5 + 6*x**3 - 3*x + 1

# Tính đạo hàm
y.backward()

print("Độ dốc tại x = 1:", x.grad.item())

Độ dốc tại x = 1: 40.0


# BTVN 02

Tạo một tensor ban đầu có giá trị là 2

Định nghĩa hàm số và tính gradient 

y = x^3 + 2x^2 + 5x + 1

Hãy tính dy/dx tại giá trị của x

Dùng phương pháp gradient descent với learning rate alpha = 0.1 để cập nhập giá trị x trong 10 vòng lặp


In [33]:
import torch

# Khởi tạo x = 2
x = torch.tensor(2.0, requires_grad=True)

# Định nghĩa hàm y
y = x**3 + 2*x**2 + 5*x + 1

# Tính đạo hàm dy/dx
y.backward()

print("Giá trị y:", y.item())
print("dy/dx tại x = 2:", x.grad.item())

Giá trị y: 27.0
dy/dx tại x = 2: 25.0


In [34]:
# Reset x
x = torch.tensor(2.0, requires_grad=True)

alpha = 0.1

for i in range(10):
    y = x**3 + 2*x**2 + 5*x + 1
    y.backward()
    
    with torch.no_grad():
        x -= alpha * x.grad   # cập nhật x
    
    x.grad.zero_()  # reset gradient
    
    print(f"Vòng {i+1}: x = {x.item():.6f}")


Vòng 1: x = -0.500000
Vòng 2: x = -0.875000
Vòng 3: x = -1.254688
Vòng 4: x = -1.725085
Vòng 5: x = -2.427826
Vòng 6: x = -3.724998
Vòng 7: x = -6.897680
Vòng 8: x = -18.912006
Vòng 9: x = -119.146408
Vòng 10: x = -4330.747559


# BTVN 03

Tạo 1 tập dữ liệu giả lập với x là số giờ học ngẫu nhiên từ 1 - 10 và y là số điểm được tính theo công thức y = 3x + 5 + noise
Với noise là một giá trị ngẫu nhiên nhỏ

1. khởi tạo tham số w và b ngẫu nhiên với requieres_grad = True
1. tính MSE
1. Tính gradient
1. Cập nhật tham số w và b bằng gradient descent với learning rate alpha = 0.01
1. Lặp lại quá trình trên trong 100 vòng lặp để xem sự hội tụ của mô hình

In [35]:
import torch

# Fix seed để dễ quan sát hội tụ
torch.manual_seed(0)

# Số mẫu
N = 50

# Dữ liệu
x = torch.rand(N) * 9 + 1          # [1, 10]
noise = torch.randn(N) * 0.5       # nhiễu nhỏ
y = 3 * x + 5 + noise

w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

def predict(x):
    return w * x + b

def mse_loss(y_pred, y_true):
    return ((y_pred - y_true) ** 2).mean()

alpha = 0.01
epochs = 100

for epoch in range(epochs):
    # Forward
    y_pred = predict(x)
    loss = mse_loss(y_pred, y)
    
    # Backward: tính gradient
    loss.backward()
    
    # Cập nhật tham số
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad
    
    # Reset gradient
    w.grad.zero_()
    b.grad.zero_()
    
    # In tiến trình
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1:3d} | Loss = {loss.item():.4f} | w = {w.item():.4f} | b = {b.item():.4f}")

Epoch  10 | Loss = 3.8913 | w = 3.7183 | b = 0.5902
Epoch  20 | Loss = 3.6232 | w = 3.6927 | b = 0.7514
Epoch  30 | Loss = 3.3751 | w = 3.6680 | b = 0.9065
Epoch  40 | Loss = 3.1456 | w = 3.6443 | b = 1.0557
Epoch  50 | Loss = 2.9331 | w = 3.6214 | b = 1.1992
Epoch  60 | Loss = 2.7366 | w = 3.5995 | b = 1.3373
Epoch  70 | Loss = 2.5547 | w = 3.5783 | b = 1.4701
Epoch  80 | Loss = 2.3864 | w = 3.5580 | b = 1.5978
Epoch  90 | Loss = 2.2306 | w = 3.5384 | b = 1.7207
Epoch 100 | Loss = 2.0865 | w = 3.5196 | b = 1.8389


# Pytorch with tensor

In [17]:
import torch
import numpy as np

In [18]:
torch.__version__

'2.8.0+cpu'

In [19]:
# Chuyển đổi mảng numpy sang tensor pytorch

arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [20]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [21]:
print(x.dtype)

torch.int64


In [22]:
print(x.type())

torch.LongTensor


In [23]:
arr2 = np.arange(0.,12).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [24]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [25]:
arr[0] = 99
print(x)

tensor([99,  2,  3,  4,  5])


In [26]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [27]:
arr[0] = 99
print(x)

tensor([0, 1, 2, 3, 4])


# BTVN 04
Giải thích 2 trường hợp ở trên

Tại vì sử dụng 2 hàm khác nhau <br>
`torch.from_numpy()` dùng chung bộ nhớ <br>
`torch.tensor()` tạo bản sao độc lập.

# BTVN 05 

Bạn giúp thầy tạo tensor với
- empty
- zeros
- random
- reshape với view và view_as


In [ ]:
a = torch.empty(3, 4)
print(a)

tensor([[-9.9621e+21,  1.2556e-42,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [37]:
b = torch.zeros(3, 4)
print(b)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [38]:
c = torch.rand(3, 4)
print(c)

tensor([[0.6962, 0.5300, 0.2560, 0.7366],
        [0.0204, 0.2036, 0.3748, 0.2564],
        [0.3251, 0.0902, 0.3936, 0.6069]])


In [ ]:
x = torch.arange(12)
y = x.view(3, 4)
print(y)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [40]:
a = torch.arange(6)
b = torch.zeros(2, 3)

c = a.view_as(b)
print(c)

tensor([[0, 1, 2],
        [3, 4, 5]])
