# DEEP LEARNING
## TUẦN 2: NUMPY, PANDAS, MATHPLOTLIB

# Numpy

In [1]:
# NUMPY là thư viện kiểu list
# Vì:
#+ numpy nhanh
#+ có nhiều hàm tích hợp dễ sử dụng cho AI

# để sử dụng numpy thì: pip install numpy
import numpy as np

In [2]:
# thử tạo 1 list
python_list = [1,2,3]

# chuyển đổi danh sách thành numpy list
numpy_list = np.array(python_list)
type(numpy_list)

numpy.ndarray

In [3]:
# list trong python có thể hỗ trợ nhiều loại dữ liệu trong list
my_list = [1, "chào", True, 2.0]

In [5]:
my_list = [1,2,3,4.5]
np_list = np.array(my_list)
np_list

array([1. , 2. , 3. , 4.5])

In [6]:
# chuyển đổi kiểu dữ liệu thì sao?
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [7]:
# accessing và indexing
x = np.array([1,2,3,4,5,6,7,8]) # x = np.array(range(1,9))

In [8]:
# lấy số 4
x[3]

np.int64(4)

In [ ]:
# lấy nhiều hơn 1 phần tử
# công thức [start:end:step]
# Lấy 1 2 3

x[0:3]

array([1, 2, 3])

In [ ]:
# lấy từ 3 - 8 theo 3 cách
# c1
x[2:8]

array([3, 4, 5, 6, 7, 8])

In [15]:
# c2
x[2:]

array([3, 4, 5, 6, 7, 8])

In [ ]:
# c3 - không đúng
x[2:-1]

array([3, 4, 5, 6, 7])

In [17]:
# lấy số 3 và số 5

x[2], x[4]

(np.int64(3), np.int64(5))

In [18]:
# đặt danh sách các index muốn truy cập
x[[2,4]]

array([3, 5])

In [20]:
data = [[1,2],[3,4],[5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
# lấy số 2
np_list[0,1]

np.int64(2)

In [ ]:
# lấy số 6
np_list[2,1]

np.int64(6)

In [34]:
# lấy [3,4], [5, 6]
# c1
np_list[1:,:]

array([[3, 4],
       [5, 6]])

In [48]:
# c2
np_list[[1,2],:]

array([[3, 4],
       [5, 6]])

In [50]:
# c3
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [63]:
# lấy 1 3 5
np_list[:,0]

array([1, 3, 5])

In [ ]:
# lấy 1 và 5 theo 2 cách
# c1
np_list[[0,2],0]

array([1, 5])

In [ ]:
# c2
np_list[0::2,0]

array([1, 5])

In [76]:
x = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
]

np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [92]:
# lấy 2 6 10 14
np_list[:, 1]

array([ 2,  6, 10, 14])

In [88]:
# lấy 7 và 11
np_list[[1,2],2]

array([ 7, 11])

In [98]:
# lấy 4 7 10
np_list[[0,1,2], [3,2,1]]

array([ 4,  7, 10])

In [ ]:
# lấy 16 15 14 13
# c1
np_list[[3,3,3,3],[3,2,1,0]]

array([16, 15, 14, 13])

In [123]:
# c2
np_list[3,::-1]

array([16, 15, 14, 13])

In [124]:
# c3
np_list[-1,::-1]

array([16, 15, 14, 13])

In [ ]:
# BTVN 01
# cho ma trận = [[99,99,99],
#                 [99,99,99],
#                 [99,99,99]]

# hãy tưởng tượng ô 99 trống
# giả sử 1 là x
# giả sử 0 là o

# lấy đầu vào từ phía x và phía o luân phiên
# nếu đầu vào từ phía x là (0,0)
# ma trận sẽ trở thành
# [[x,99,99],
# [99,99,99],
# [99,99,99]]

# nếu đầu vào từ phía o là (0,0)
# thông báo họ nhập lại 
# nếu không thì điền vào ma trận

# thử thách: nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi

In [ ]:
# BTVN 2
# cho y = [[1,2,3],
#         [4,5,6],
#         [7,8,9]]

# lấy 4,5,6
# lấy 2,5
# lấy 3,4
# lấy 9,6,3

In [ ]:
# BTVN 3
# x = [1,2,3,4,5,6,7,8,9,10]

# 1. xuất ra các giá trị chẵn sử dụng if
# 2. xuất ra các giá trị chẵn sử dụng list comprehension

In [125]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np_x[np_x % 2 == 0]

array([0, 2, 4, 6, 8])

In [127]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [131]:
idx = [ True, True,  True, False,  True, True,  True, False,  True, False]

In [132]:
np_x[idx]

array([0, 1, 2, 4, 5, 6, 8])

In [133]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0

np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# BTVN 4
# tạo 1 mảng numpy có kích thước 150 x 5. Giả sử mã này chứa 150 mẫu dữ liệu của sinh viên bao gồm chiều cao, cân nặng, tuổi, lương và điểm trung bình
# tách mảng dựa trên 4 cột đầu tiên thành một biến có tên là x và cột cuối cùng là y

# tách x thành x_train, x_test trong đó x_train chứa 70% dữ liệu và tách y thành y_train, y_test trong đó y_train chứa 70% dữ liệu

# tạo 10 tập dữ liệu x_train không chồng chéo nhau