# DEEP LEARNING
## TUẦN 2: NUMPY, PANDAS, MATHPLOTLIB

# Numpy

In [1]:
# NUMPY là thư viện kiểu list
# Vì:
#+ numpy nhanh
#+ có nhiều hàm tích hợp dễ sử dụng cho AI

# để sử dụng numpy thì: pip install numpy
import numpy as np

In [2]:
# thử tạo 1 list
python_list = [1,2,3]

# chuyển đổi danh sách thành numpy list
numpy_list = np.array(python_list)
type(numpy_list)

numpy.ndarray

In [3]:
# list trong python có thể hỗ trợ nhiều loại dữ liệu trong list
my_list = [1, "chào", True, 2.0]

In [5]:
my_list = [1,2,3,4.5]
np_list = np.array(my_list)
np_list

array([1. , 2. , 3. , 4.5])

In [6]:
# chuyển đổi kiểu dữ liệu thì sao?
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [7]:
# accessing và indexing
x = np.array([1,2,3,4,5,6,7,8]) # x = np.array(range(1,9))

In [8]:
# lấy số 4
x[3]

np.int64(4)

In [ ]:
# lấy nhiều hơn 1 phần tử
# công thức [start:end:step]
# Lấy 1 2 3

x[0:3]

array([1, 2, 3])

In [ ]:
# lấy từ 3 - 8 theo 3 cách
# c1
x[2:8]

array([3, 4, 5, 6, 7, 8])

In [15]:
# c2
x[2:]

array([3, 4, 5, 6, 7, 8])

In [ ]:
# c3 - không đúng
x[2:-1]

array([3, 4, 5, 6, 7])

In [17]:
# lấy số 3 và số 5

x[2], x[4]

(np.int64(3), np.int64(5))

In [18]:
# đặt danh sách các index muốn truy cập
x[[2,4]]

array([3, 5])

In [20]:
data = [[1,2],[3,4],[5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
# lấy số 2
np_list[0,1]

np.int64(2)

In [ ]:
# lấy số 6
np_list[2,1]

np.int64(6)

In [34]:
# lấy [3,4], [5, 6]
# c1
np_list[1:,:]

array([[3, 4],
       [5, 6]])

In [48]:
# c2
np_list[[1,2],:]

array([[3, 4],
       [5, 6]])

In [50]:
# c3
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [63]:
# lấy 1 3 5
np_list[:,0]

array([1, 3, 5])

In [ ]:
# lấy 1 và 5 theo 2 cách
# c1
np_list[[0,2],0]

array([1, 5])

In [ ]:
# c2
np_list[0::2,0]

array([1, 5])

In [76]:
x = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
]

np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [92]:
# lấy 2 6 10 14
np_list[:, 1]

array([ 2,  6, 10, 14])

In [88]:
# lấy 7 và 11
np_list[[1,2],2]

array([ 7, 11])

In [98]:
# lấy 4 7 10
np_list[[0,1,2], [3,2,1]]

array([ 4,  7, 10])

In [ ]:
# lấy 16 15 14 13
# c1
np_list[[3,3,3,3],[3,2,1,0]]

array([16, 15, 14, 13])

In [123]:
# c2
np_list[3,::-1]

array([16, 15, 14, 13])

In [124]:
# c3
np_list[-1,::-1]

array([16, 15, 14, 13])

In [ ]:
# BTVN 01
# cho ma trận = [[99,99,99],
#                 [99,99,99],
#                 [99,99,99]]

# hãy tưởng tượng ô 99 trống
# giả sử 1 là x
# giả sử 0 là o

# lấy đầu vào từ phía x và phía o luân phiên
# nếu đầu vào từ phía x là (0,0)
# ma trận sẽ trở thành
# [[x,99,99],
# [99,99,99],
# [99,99,99]]

# nếu đầu vào từ phía o là (0,0)
# thông báo họ nhập lại 
# nếu không thì điền vào ma trận

# thử thách: nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi

In [1]:
import numpy as np

board = np.full((3,3), 99, dtype=int)

def print_board(b):
    sym = {99:'.', 1:'X', 0:'O'}
    for r in range(3):
        print(' '.join(sym[int(v)] for v in b[r]))
    print()

def is_winner(b, p):
    # hàng
    if np.any(np.all(b == p, axis=1)): return True
    # cột
    if np.any(np.all(b == p, axis=0)): return True
    # chéo chính
    if np.all(np.diag(b) == p): return True
    # chéo phụ
    if np.all(np.diag(np.fliplr(b)) == p): return True
    return False

def valid_move(b, r, c):
    return 0 <= r < 3 and 0 <= c < 3 and b[r, c] == 99

def play():
    current = 1  # X bắt đầu
    moves = 0
    while True:
        print_board(board)
        player = 'X' if current == 1 else 'O'
        try:
            s = input(f"Người {player} nhập hàng,cột (ví dụ 0 0): ").strip()
            r, c = map(int, s.split())
        except:
            print("Nhập không hợp lệ. Thử lại.")
            continue
        if not (0 <= r < 3 and 0 <= c < 3):
            print("Tọa độ ngoài phạm vi. Thử lại.")
            continue
        if not valid_move(board, r, c):
            print("Ô đã có người đi. Nhập lại.")
            # nếu O cố nhập ô đã có, yêu cầu nhập lại (không đổi lượt)
            continue
        board[r, c] = current
        moves += 1
        if is_winner(board, current):
            print_board(board)
            print(f"Người {player} thắng!")
            break
        if moves == 9:
            print_board(board)
            print("Hòa.")
            break
        current = 0 if current == 1 else 1

if __name__ == "__main__":
    play()


. . .
. . .
. . .

X . .
. . .
. . .

X O .
. . .
. . .

X O .
. X .
. . .

X O .
. X O
. . .

X O .
. X O
. . X

Người X thắng!


In [4]:
# BTVN 2
# cho y = [[1,2,3],
#         [4,5,6],
#         [7,8,9]]

# lấy 4,5,6
# lấy 2,5
# lấy 3,4
# lấy 9,6,3

y = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])

y[1,:]

array([4, 5, 6])

In [5]:
y[[0,1],1]

array([2, 5])

In [6]:
y[[0,1], [2,0]]

array([3, 4])

In [7]:
y[[2,1,0], 2]

array([9, 6, 3])

In [8]:
# BTVN 3
# x = [1,2,3,4,5,6,7,8,9,10]

# 1. xuất ra các giá trị chẵn sử dụng if
# 2. xuất ra các giá trị chẵn sử dụng list comprehension

x = [1,2,3,4,5,6,7,8,9,10]
evens = []
for v in x:
    if v % 2 == 0:
        evens.append(v)
print(evens)

[2, 4, 6, 8, 10]


In [9]:
evens = [v for v in x if v % 2 == 0]
print(evens)

[2, 4, 6, 8, 10]


In [125]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np_x[np_x % 2 == 0]

array([0, 2, 4, 6, 8])

In [127]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [131]:
idx = [ True, True,  True, False,  True, True,  True, False,  True, False]

In [132]:
np_x[idx]

array([0, 1, 2, 4, 5, 6, 8])

In [133]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0

np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# BTVN 4
# tạo 1 mảng numpy có kích thước 150 x 5. Giả sử mã này chứa 150 mẫu dữ liệu của sinh viên bao gồm chiều cao, cân nặng, tuổi, lương và điểm trung bình
# tách mảng dựa trên 4 cột đầu tiên thành một biến có tên là x và cột cuối cùng là y

# tách x thành x_train, x_test trong đó x_train chứa 70% dữ liệu và tách y thành y_train, y_test trong đó y_train chứa 70% dữ liệu

# tạo 10 tập dữ liệu x_train không chồng chéo nhau

In [ ]:
import numpy as np

# tạo dữ liệu giả (150 x 5): [height, weight, age, salary, gpa]
rng = np.random.default_rng(42)
data = np.empty((150,5))
# ví dụ phân phối hợp lý:
data[:,0] = rng.normal(170, 10, 150)      # height (cm)
data[:,1] = rng.normal(65, 12, 150)       # weight (kg)
data[:,2] = rng.integers(18, 30, 150)     # age (yrs)
data[:,3] = rng.normal(8_000, 2_000, 150) # salary
data[:,4] = np.clip(rng.normal(3.0, 0.5, 150), 0.0, 4.0)  # gpa

# tách X và y
X = data[:, :4]
y = data[:, 4]

# trộn dữ liệu trước khi chia (giữ reproducible)
idx = rng.permutation(150)
X = X[idx]
y = y[idx]

# chia 70% train, 30% test
n_train = int(0.7 * 150)  # 105
X_train = X[:n_train]
X_test  = X[n_train:]
y_train = y[:n_train]
y_test  = y[n_train:]

# tạo 10 tập X_train không chồng chéo nhau (chia X_train thành 10 nhóm gần đều)
fold_sizes = np.full(10, n_train // 10, dtype=int)  # base size = 10
remainder = n_train % 10                              # 5
fold_sizes[:remainder] += 1                           # đầu các fold nhận 1 phần tử thêm

# tách theo fold_sizes
x_train_splits = []
start = 0
for sz in fold_sizes:
    end = start + sz
    x_train_splits.append(X_train[start:end])
    start = end

for i, split in enumerate(x_train_splits, 1):
    print(f"--- Split {i}: shape = {split.shape} ---")
    print(split[:10])
    print()

--- Split 1: shape = (11, 4) ---
[[  167.24857749    54.88123676    26.          8785.65493652]
 [  174.56775238    47.43869598    19.         12153.96105811]
 [  160.73424059    68.1529907     29.          6561.03953343]
 [  161.34168884    54.4621716     29.          8949.39417693]
 [  176.65385109    54.47767066    29.          3854.03312802]
 [  178.38126568    65.62960158    24.          4878.08329401]
 [  174.14409433    61.97627146    22.          7827.79869636]
 [  172.18688597    54.26327577    19.          7861.72413055]
 [  166.80328784    72.72726552    19.          9607.17003876]
 [  180.65980231    43.91933861    18.          6224.60868857]]

--- Split 2: shape = (11, 4) ---
[[  172.37735602    61.80335012    26.          7886.43361121]
 [  177.37515568    53.15771506    19.         10127.70306547]
 [  166.10190197    70.76172084    24.          4994.99308792]
 [  153.17130228    75.99083051    20.          4338.1883483 ]
 [  164.87757271    60.06887323    27.          74